version: '3.1'

services:
  proxy:
    image: koxudaxi/local-data-api:latest
    container_name: nawr-proxy
    restart: always
    environment:
      ENGINE: PostgreSQLJDBC
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      RESOURCE_ARN: 'arn:aws:rds:us-east-1:123456789012:cluster:dummy'
      SECRET_ARN: 'arn:aws:secretsmanager:us-east-1:123456789012:secret:dummy'
    ports:
      - "8080:80"
  db:
    image: postgres:10.7-alpine
    container_name: nawr-db
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: master
    ports:
        - "5432:5432"

  workers:
    build: /home/hobochild/Play/nawr/worker
    container_name: nawr-workers
    restart: always
    volumes:
      - ${PWD}:/usr/src/app/nawr
      - /home/hobochild/Play/nawr/worker/server.js:/usr/src/app/server.js
    ports:
        - "8081:8081"
